### ISSUE TITLE
Types for lifted functions that preserve concrete-ness

### ISSUE THREAD

**Issue by AlexKnauth** [stchang/typed-rosette#10]
Right now these types have to be represented as `Ccase->` types, and there is no way for the user to construct a new function with a `Ccase->` type. So there are two issues.

* Should we stick with just `Ccase->` and accept that there are going to be a bunch of types which look like `(Ccase-> (C-> CA ... CB) (C-> A ... B))`, or should we implement some kind of "concreteness polymorphism" like `(∀/Symbolicness/Concreteness (X) (C-> (X A) ... (X B)))`?

* We need to allow users to construct functions with these types. Adding `case-lambda` doesn't solve this. Most of these are cases where the same `body` needs to be type checked multiple times against different environments with different expected types:
```racket
[[a : CA] ... ⊢ body ⇐ CB]
[[a : A] ... ⊢ body ⇐ B]
```

We would probably end up doing something similar to this anyway for other `Ccase->` purposes, using a rule similar to what we already do for `#%app` of union functions. 

Would this be easier or harder with some notion of concreteness polymorphism? Or are we better off reusing the `Ccase->` rules?

**Comment by stchang** [comment]
I like the concrete/symbolic polymorphism idea.

It might be messy though since "concrete" and "symbolic" are not explicit constructors?

**Comment by AlexKnauth** [comment]
Would it make sense to provide `∀/Symbolicness/Concreteness` as a macro to expand into `case->` in the correct way?

**Comment by stchang** [comment]
What if there is more than one type variable? Expand into a `case->` covering every combination?

**Comment by AlexKnauth** [comment]
The places where there are more than one concreteness parameter will be rare. Most of the time the only thing you're worried about keeping concrete is the one output. And when the output has multiple types in it that could be concrete, most of the time they will be concrete together, or symbolic together. For the times when that's not true, it will need to go into combinations.

**Comment by stchang** [comment]
Ok let's just support one parameter for now.

**Comment by AlexKnauth** [comment]
My current simplified plan for user-created `Ccase->` functions looks like this rule:
```racket
[[x ≫ x- : τ_in] ... ⊢ body ≫ body- ⇐ τ_out]
...
---------
[⊢ (λ (x:id ...) body) ≫ (λ- (x_??? ...) body_???) ⇐ (~Ccase-> (~C→ τ_in ... τ_out) ...)]
```
The problem is the `x-`s and the `body-`s. Where do they go? What should the `x_???` and the `body_???` be? If the `body-`s do their own type-based elaborations like looking up typeclass implementations, then none of them will be correct for the whole.

One thing I'm thinking about is type checking the body against every case, and then type checking it one more time against the union of all those cases. That rule would look like this:
```racket
[[x ≫ _ : τ_in] ... ⊢ body ≫ _ ⇐ τ_out]
...
#:with [[τ_in* ...] ...] (transpose #'[[τ_in ...] ...])
[[x ≫ x- : (U τ_in* ...)] ... ⊢ body ≫ body- ⇐ (U τ_out ...)]
---------
[⊢ (λ (x:id ...) body) ≫ (λ- (x- ...) body-) ⇐ (~Ccase-> (~C→ τ_in ... τ_out) ...)]
```

One thing that worries me is that this won't work for functions that rely on one specific argument being concrete in every case. That could be mitigated by using a type constructor that expanded to `CU` when given concrete types but `U` otherwise. Does this seem like the best way, or is there a better way to handle this?

**Comment by stchang** [comment]
implemented with https://github.com/stchang/typed-rosette/commit/ec6dc496890866267c83d09dfac1e1844d9df994
