### ISSUE TITLE
Unsoundness from for/all

### ISSUE THREAD

**Issue by AlexKnauth** [stchang/typed-rosette#12]
In this program:
```
(: f : (C→ PosInt PosInt))
(define (f x)
  (for/all ([y x])
    (expect-concrete y)))

(define-symbolic symb-x integer?)
(f (assert-type symb-x : PosInt))
```
The `for/all` takes away the `U` from `PosInt` and binds `y` with type `CPosInt`, even though at run time it's bound to a symbolic constant `symb-x`.

**Comment by stchang** [comment]
Yes, I realized this as well while trying to fix `for/all` myself.

I think this is a repercussion of our conflation, from the type perspective, of unsolvable symbolic unions and solvable symbolic values.

A programmer is supposed to use `for/all` to destructure symbolic unions only. Ideally, during typechecking of `for/all`, we should be able to take each element of a symbolic union type (eg, each `ty` in a `(U ty ...)`, where `ty` itself could be symbolic) and typecheck that against the body of the `for/all` (and maybe even drop the ones that fail, to correspond with rosette's merging). Then all the resulting types should be recombined into another symbolic union.

But with our current design, with just one `U` for both symbolic unions and solvable symbolic values (and the flattening that we do), we get some unsound corner cases.

Not sure what to do. I think we might have to abandon our single `U` approach and distinguish unsolvable symbolic unions and solvable symbolic values (ie, values where `term?` returns true) at the type level.

That's a significant change so let's think about it and discuss more tomorrow.

**Comment by AlexKnauth** [comment]
We might have to distinguish between possibly-`term?` and possibly-`union?` in order to do `for/all` correctly.

However I don't think we can take each element of the symbolic union type like you say. We should combine them into some kind of concrete union. If the `union?` contains only concrete elements, then that works. But if the `union?` contains `term?` elements, then we would be right to give it a symbolic type so that the body can't rely on it being concrete.

Also, we will never be able to drop branches with type errors in them, because not every type error is an immediate run time error. It could be further down in a branch, or it could be in a lambda. Even if that were true and there was an immediate run time error every time, we should still treat it differently from `(assert #false)`, because unlike `(assert #false)`, it is probably a programmer mistake.

**Comment by stchang** [comment]
> We might have to distinguish between possibly-term? and possibly-union? in order to do for/all correctly.

Yes, that's what I was getting at. `term?` distinguishes solvable symbolic values while symbolic unions are unsolvable. I think `for/all` is important to get right so I think we will have to fix our types to similarly distinguish `term?` and `union?` categorizations.

>  if the union? contains term? elements

I agree and I did say that `ty` itself could be symbolic. My `U` above is a hypothetical new symbolic union type that corresponds to symbolic union values only (and is not flattened like we do now), though we'll have to think about the details.

> we will never be able to drop branches with type errors

I was just speculating so I dont know if it would work overall, but I can think of some cases where it would apply, eg.

```racket
$ racket
Welcome to Racket v6.7.0.4.
> (require rosette)
> (define-symbolic b boolean?)
> (for/all ([s (if b 1 "one")]) (string-append s "two"))
"onetwo"
```

My hypothetical `for/all` rule would try to typecheck the body using `s : CInt` and `s : CString`, which are the components of the symbolic union. The former would fail, so the resulting type would just be CString, matching up with Rosette's behavior.

**Comment by stchang** [comment]
Ok here's how I think we should overhaul our types.

In hindsight, we probably tried to be a little too clever with our initial design.

Let's try a more naive, straightforward approach, at least until we get several good working examples ported.

1) Drop the `Nat`, `NegInt`, `Zero`, etc distinctions. They are causing problems like you said, and even worse, these problems are unnecessary and not that important to typing Rosette. Plus they dont play well with mutability, which gets used a lot.

    We can try to add them back later when things are more mature.

    This means `#%datum` needs reimplementation though.

2) Define base types (not aliases) that exactly match up with Rosette's solvable types: `CInt`, `Int`, `CReal`, `Real`, `CBV`, `BV`, `CBool`, `Bool`. (`Bool` can remain an alias if you think it would help occurrence typing, since `#f` is a commonly used literal).

3) Change the symbolic union type so that it represents only symbolic union values. I guess it should still be flattened since Rosette flattens symbolic unions, but flattening should not improperly take away the symbolicness of the constituent types like in your initial example.

    This means that `if` will need special cases for each solvable type I think, but I think this is the right approach for now. We can think about how to refactor to remove code duplication later.

4) The `concrete?` predicate will change to `(not (or Real? BV? Bool? Int? U? Any?))`

5) The other types --- containers, functions, and concrete unions --- can remain unchanged I believe.

6) I think the `solvable?` property can perhaps be eliminated and replaced with `(or Real? Bool? Int?)`? (`BV` should be excluded?)

What do you think about this plan?

**Comment by AlexKnauth** [comment]
I agree with some of it but I think it could be better. I don't like the many special cases of `Int`, `Real`, `BV`, and `Bool` as base types. We could replace that with a `(Term X)` type constructor:
```racket
(define-symbolic x integer?)
; x : (Term CInt)
; (if b x -3) : (Term CInt)
```
The meaning of `Term` would be possibly-`term?`, so a function expecting `(Term CInt)` would be fine with `-3` or `(if b -3 6)`. The `Term` constructor will be a macro to restrict its inputs and exclude non-solvable types like `(CListof X)`.

(Question: Should `BV` count as solvable? It doesn't fully specify a *shape type*, meaning two `BV`s merging together would form a `union?`. That would normally exclude it from being solvable, but there are also `term?`s that would have no other type but `(Term CBV)`. How should this be treated?)

The symbolic union type `U` would work like you say, only representing possibly-`union?` values and not taking away `Term` constructors from its constituents.
```racket
(define-symbolic x integer?)
(define-symbolic b b1 boolean?)
; x : (Term CInt)
; b : (Term CBool)
; (if b1 b x) : (U (Term CBool) (Term CInt))
; (if b1 #true -3) : (U CBool CInt)
```
Types like `BV` don't fully specify a single shape type, so `(U (Term CBV))` has to remain as a "single element" union type. Same for types like `(U (CListof X))`.

The `if` rule for symbolic test-exprs would combine the two branches using a type merging function. This function would produce `U` unless the two types are the same shape type. This means `CBV` would be put in a union, but `CInt` would not.

Two `CBV` values would result in `(U CBV)`, and two `(Term CBV)` values would result in `(U (Term CBV))`. However, two `CInt` or `(Term CInt)` values would result in `(Term CInt)`. 

Then there are types like the heterogeneous `List` type which specify a single shape type, but are not solvable. These would be the ones that benefit from merging within sub-parts of the type. The merging would take `(CList A B C)` and `(CList D E F)` and produce `(CList #,(merge A D) #,(merge B E) #,(merge C F))`.

**Comment by stchang** [comment]
Ok so essentially you are separating the old `U` wrapper into two wrappers: new `U` and `Term`. I guess that would be ok. Everything else you said sounds fine.

Agree with `BV` being unsolvable for now (ie, use `U` instead of `Term`). It seems like bvs are not used much anyways so let's not waste too much time on it.

Also, feel free to start off with a naive placeholder merging function initially. Let's push through the change to the types first before tackling the other stuff.

**Comment by AlexKnauth** [comment]
How should function types fit into this? Two symbolic function values of the same solvable type will be merged in a union, which means it can't be a shape type. However, they still need to have `Term` types other than unions because of how `for/all` works.

So I guess that means not all solvable types are shape types. We will need predicates for both of them. Solvable types are types that can appear within `(Term X)`, and shape types are types that can be merged without creating a union, but neither implies the other.

Functions and bvs, I think, are two examples of types that are solvable, but don't represent shape types.

**Comment by stchang** [comment]
Right, I dont think there's any relation between solvability and mergability.

**Comment by AlexKnauth** [comment]
What about integers and reals? The expression `(if b 3 3.14)` has type `Num`, but evaluates to a symbolic union. That means that `Num` can't really be a shape type either.

(Edit: so does `(if b 3.0 3.14)` by the way)

**Comment by stchang** [comment]
So maybe `U` should only prune based on `type=?` and not `typecheck?`? That way, `(if b 3 3.14)` will have type `(U CInt CNum)`.

**Comment by AlexKnauth** [comment]
No, that doesn't solve the problem. It just means you would need some annotation or function in between:
```racket
(: f : (C-> (Term CNum) (Term CNum) (Term CNum)))
(define (f x y)
  (if b x y))

(f 3.0 3.14)
```
This has the same unsoundness returning a union, but `x` and `y` have the same type in the `if` statement.

Making `CNum` not a shape type makes the `if` statement return `(U (Term CNum))`, triggering the type error we want.

**Comment by stchang** [comment]
Ok, so would `(if b 1.1 1.2)` have type `(U CNum)` or `(Term CNum)`?

**Comment by AlexKnauth** [comment]
Under the system I have in mind it would have type `(U (Term CNum))`, even though at run time it produces a `term?`.

**Comment by stchang** [comment]
Could you add a special case for `CNum` in `if`?

**Comment by AlexKnauth** [comment]
Here's something else we need to be careful of:

Defining symbolic types as symbolic unions of concrete types like we've done before is only sound when there is *no* possibility that the value contains a `term?` element. That means that if Rosette's merging behavior ever changes, for instance merging strings with `ite`s instead of unions, then the previously sound `(define-named-type-alias String (U CString))` could become unsound.

**Comment by stchang** [comment]
If the semantics of the language changes then all bets are off with respect to type system soundness.

But good too keep these cases in mind nonetheless.

**Comment by AlexKnauth** [comment]
There's another potential problem with occurrence typing interacting with `for/all`. If occurrence typing is used to pick a branch of a symbolic union, then it will still be a one-element union type, because the runtime value will still be a union. Then the `for/all` form can take that union away and turn it into the concrete type. However, the body will still be run for each case of the original union, including things that aren't that concrete type.

```
(define-symbolic b boolean?)

(: f : (C-> (U CInt (Term CBool)) BV))
(define (f x)
  ;; x : (U CInt (Term CBool))
  ;; RUNTIME x = (union 3 b)
  (if (integer? x)
      ;; here, x : (U CInt)
      ;; RUNTIME and still x = (union 3 b)
      ;;   (with a path condition that will constrain it to the 3 branch)
      (for/all ([x x])
        ;; here, x : CInt
        ;; RUNTIME this will run twice:
        ;;   Case 1:  x = 3, fine.
        ;;   Case 2:  x = b, UNSOUND!
        ;;     (with an path condition that would be infeasible if solved)
        (bv 0 x))
      ;; here, x : (U (Term CBool))
      (bv 0 1)))

(f (union 3 b))
```

The unsoundness happens within an infeasible path condition, but it will try to evaluate it anyway because the solver isn't called within normal evaluation.

Thankfully this only raises an exception that `for/all` will catch, and it would only raise an exception in a place where the path condition is infeasible anyways. So because of `for/all`'s behavior, this remains "safe" and does not impact behavior. However if that changes and type-based optimizations are used, this could result in a segfault.

**Comment by stchang** [comment]
I dont think the example is quite right. Specifically, I dont think case 2 happens.

Because with symbolic unions, isnt the path already explicit in the union value? So in the "then" branch, the union value is already adjusted to exclude non-ints, eg

```racket
$ racket
Welcome to Racket v6.7.0.4.
> (require rosette)
> (define-symbolic b boolean?)
> (define (f x) (if (integer? x) (for/all ([x x]) (begin(displayln x)(bv 0 x))) (bv 0 1)))
> (f (if b 3 "3"))
3
{[b (bv 0 3)] [(! b) (bv 0 1)]}
> (asserts)
'()
>
```

**Comment by AlexKnauth** [comment]
Case 2 doesn't happen for that program. However all you need to do is a little bit of fiddling to get out of that special case. You could replace the test `(integer? x)` with `(or (integer? x) unsat-expr)`, where `unsat-expr` is any expression that the type system knows is symbolic false but that rosette doesn't figure out is unsat until solving time.

**Comment by AlexKnauth** [comment]
What should happen when `for/all` is given a multi-case union type with at least one `Term` case?
```racket
(define-symbolic x1 integer?)
;; x1 : (Term CInt)

(define (f0 [x : (U (Term CInt) CFalse)]) -> (U (Term CInt) CFalse)
  (for/all ([y x])
    ;; y : ???
    y))
```

In this case the body of the `for/all` will be evaluated multiple times, and on any given time you don't know which case it will be, but you know it will be one and only one of the cases. That's exactly the meaning of `CU`, the concrete union, except that some of the cases will not be concrete.

It's the same as the difference between `f1` and `f2` here:
```racket
(define (f1 [cb : CBool]) -> ???
  (if cb x1 #f))

(define (f2 [b : Bool]) -> (U (Term CInt) CFalse)
  (if b x1 #f))
```

Should `(CU (Term CInt) CFalse)` would be a legal type? That would be the type of `y` in the first example, and the return type of `f1` in the second. It's meaning would be that in any given time it's evaluated, it will either be a `(Term CInt)` or a `CFalse` but never a `union?`.

If not, what should we use to express cases where it's either one symbolic term or another, but never a `union?` of the two?

**Comment by stchang** [comment]
If we allowed `(CU (Term CInt) CFalse)`, then the issue would be that `concrete?` would need to go all the way down instead of just looking at the outer constructor?

Also, why can't `for/all` typecheck the body against each of the types and then union the results?

**Comment by AlexKnauth** [comment]
Okay. It's not really necessary to change `CU`, so I'll leave it as is.
