### ISSUE TITLE
`begin` doesnt transfer props?

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#19]
Instead of re-using from `ext-stlc`, Typed Rosette should implement it's own `begin` now, right?

**Comment by stchang** [comment]
Nm, I misunderstood how `with-occurrence-env` worked.

**Comment by AlexKnauth** [comment]
No, this is still a problem.

**Comment by stchang** [comment]
Oh ok.

In my case I was having a problem with occurrence typing not working with `when` and `unless`. I think it is due the the `delta-introducer` using the `begin` added by `when` and `unless`. I changed it to look something like below and it seems to be working now
```
  [(_ condition:expr body:expr ...+) ≫
   [⊢ condition ≫ condition- (⇒ prop+ posprop)]
   #:with e (datum->stx #'condition (cons 'begin #'(body ...)))
   [⊢ (with-occurrence-prop posprop e) ≫ body- ⇒ τ]
   --------
   [⊢ (ro:when condition- body-) ⇒ (U τ CVoid)]]
```

**Comment by AlexKnauth** [comment]
Oh, I see now. This is a completely different problem that will affect a completely different use of `begin`. It affects things like
```racket
(: f : (C→ Any Int))
(define (f x)
  (if (begin (integer? x))
      x                     ; broken
      0))
```
Instead of
```racket
(: f : (C→ Any Int))
(define (f x)
  (if (integer? x)
      (begin x)             ; fine
      0))
```

**Comment by stchang** [comment]
Ah ok. Yes that's a problem too.
