### ISSUE TITLE
`CFalse` wrapped with `Term`

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#21]
This function fails to type check because `CFalse` gets wrapped with `Term`:

```racket
#lang typed/rosette

(define-type-alias Key (U CFalse CSymbol))
(define-type-alias Val (U CFalse CSymbol CInt))

(define (ref [k1 : Key] [k2 : Key] [val : Val]) -> Val
  (if (equal? k1 k2) val #f))
```
=>
```
ann: type mismatch: expected Val, given (U CSymbol CNegInt CPosInt CZero (Term False))
   expression: (begin (if (equal? k1 k2) val #f))
```

**Comment by stchang** [comment]
I inserted an extra clause `[(types-same-singleton? a b) a]` in `type-merge/single-shape-solvable`.

**Comment by AlexKnauth** [comment]
Or would changing line 818 to use the normal type-merge fix it as well?

https://github.com/stchang/typed-rosette/blob/master/typed/rosette/types.rkt#L818

**Comment by stchang** [comment]
Yes I believe that would work. Is `type-merge/single-shape-solvable` still needed then?

**Comment by stchang** [comment]
fixed in https://github.com/stchang/typed-rosette/commit/115b97931e045f62042615ecd72df3bbc26d992a
