### ISSUE TITLE
bad syntax when defining value with `define` and existing name

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#26]
A definition like `(define var 1)` produces `var: bad syntax`, when `var` is an existing macro.

It's because `define` now expands the identifier first, using the `id/type-decl` stx class. I'm guessing it's needed because of `:` but is there a way to make the err message better?

**Comment by AlexKnauth** [comment]
I could define a new structure type specially for `:` type declarations, and then use `syntax-local-value` instead of `local-expand`.

**Comment by AlexKnauth** [comment]
With #27, `(define var 1)` now succeeds. Is that what you expected, or do you want an error message?

**Comment by stchang** [comment]
Yes succeed is better thanks
