### ISSUE TITLE
mutable data structure unsoundness

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#3]
@AlexKnauth Not sure how to resolve this other than to disallow concrete types as the elements of mutable data structures?

(example from Ch 8 of the guide)
```racket
#lang typed/rosette
(define y (vector 0 1 2)) ; y correctly has type (CMVectorof CNat)
(define-symbolic b boolean?)

(if b
    (vector-set! y 1 3)
    (vector-set! y 2 4))

;; y is now (vector 0 (if b 3 1) (if b 2 4))), which should have type (CMVectorof Nat),
;; ie a concrete vector of (possibly) symbolic Nats,
;; but y incorrectly still has type (CMVectorof CNat)
y
```

**Comment by AlexKnauth** [comment]
Oh, good point. Would a good way to deal with this be to require mutable things to be possibly-symbolic?

**Comment by stchang** [comment]
> Would a good way to deal with this be to require mutable things to be possibly-symbolic

Yes that's what I was thinking, but I guess we'll have to see if the loss of precision makes the type system less useful.

**Comment by stchang** [comment]
Alternatively, could we keep track of some path state in a lightweight but sound way?

Like what if, when an `if` test is possibly symbolic, we propagate that information to the branches?

**Comment by stchang** [comment]
@AlexKnauth Actually, all `set!` operations are currently unsound, eg:

```racket
(define x 10)
(if b (set! x 11) (set! x 12))
x ; has value (if b 11 12) but still has type CNat
```

Since we cant restrict the type of `x` to be non-concrete, we would have to do something like what I proposed above.

**Comment by AlexKnauth** [comment]
Yes, exactly. Mutability can make things symbolic even when only `set!`-ing it to concrete values.

**Comment by stchang** [comment]
Ok I'll see if I can come up with a solution.

**Comment by stchang** [comment]
So on the call today, were you thinking of adding a `Mutable` type constructor that would wrap other types? That might have the side benefit of allowing us to get rid of all the "M" versions of all the other types.

**Comment by AlexKnauth** [comment]
No, I was thinking of keeping all the type structures the same, and modifying the type rules so that they made sure it was possibly-symbolic. For example the type rule for `box` would be
```
⊢ e ⇒ τ
--------
⊢ (box e) ⇒ (Boxof (U τ))
```
Or alternatively, we could change the type constructors so that they did this wrapping automatically.

A `Mutable` type constructor could be an interesting idea, but I don't see how it would help solve this.

**Comment by stchang** [comment]
> modifying the type rules so that they made sure it was possibly-symbolic

But this doesnt handle the `set!` example from https://github.com/stchang/typed-rosette/issues/3#issuecomment-290473443 above right?

That's why I think we need a general "mutable" modifier

**Comment by AlexKnauth** [comment]
That would include the `define` and `set!` rules. I was thinking of adding a syntax property for variable mutability, and the `set!` rule would only succeed when that syntax property is there. The `define` and `:` macros would take a special syntax for declaring it mutable, and would both attach this syntax property and enforce that it's possibly-symbolic.

**Comment by stchang** [comment]
Ok I think my Mutable is essentially the same as your stx prop then. Except one is explicit and we'll have to modify the type check relation to handle  it and the other is implicit and we need to modify a bunch of forms to propagate it. We'll have to think about which has better tradeoffs. For example i think an explicit constructor might handle subtyping more smoothly?

**Comment by stchang** [comment]
@AlexKnauth Are you working on this? Otherwise I will, but don't want to duplicate effort.

**Comment by AlexKnauth** [comment]
Yes. I'm making it so that it attaches a syntax property when you say
```
(: x #:mutable : Int)
(define x 0)
```

**Comment by stchang** [comment]
ok i will wait for you to push then.

I'm working on allowing mutable structs, so i will make sure to wrap the mutable fields with `U`

**Comment by stchang** [comment]
Hmm, actually, is the `#:mutable` property even necessary? We could just disallow `set!` of concrete-typed values. The programmer could get around this by annotating the variable with a possibly-symbolic type.

**Comment by AlexKnauth** [comment]
With a fix for this, can `(box 1)` have still a subtype of `CAny`? It must be able to hold symbolic values because of possible mutation under `if`s. So should I delete this test in `rosette-tests.rkt`?
```racket
;; data structures have type CAny only if elements are concrete
;; (even if outer structure is concrete)
(check-type (box 1) : CAny)
```
And replace it with `check-not-type`?

**Comment by stchang** [comment]
yes delete

EDIT: actually, replace it with `check-not-type ... CAny`

**Comment by AlexKnauth** [comment]
Okay. I have it pushed to https://github.com/AlexKnauth/typed-rosette/tree/mut, but the Travis is failing because the Github mirror of Macrotypes hasn't updated to include my commit providing `~True` and `~False`.

**Comment by stchang** [comment]
travis uses git head

**Comment by AlexKnauth** [comment]
It uses the head of the Github mirror, not the head of the Bitbucket source.

**Comment by stchang** [comment]
Ok I fixed it. restart travis

**Comment by AlexKnauth** [comment]
Should we push to both repositories (Github and Bitbucket) whenever we push to one?

**Comment by AlexKnauth** [comment]
Fixed by https://github.com/stchang/typed-rosette/pull/7

**Comment by stchang** [comment]
> Should we push to both repositories

That's what I do. There should be a way to automate it but I haven't figured out how yet.
