### ISSUE TITLE
add CAny type

### ISSUE THREAD

**Issue by stchang** [stchang/typed-rosette#4]
@AlexKnauth Have you merged `CAny` yet? If not, would it be easy for you to do so?

I'm finding myself needing it as well so I can add it too if you dont want to.

**Comment by AlexKnauth** [comment]
I haven't been working on `CAny`; I worked around it by splitting a function into two.

**Comment by stchang** [comment]
Ok I'll add it. It would help the precision of many built-in fns (which is more awkward to split).
